name: boatematica
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_gifimage: ^1.0.1

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true
  assets:
      - assets\background.gif
      - assets\botao_play.png
      - assets\botao_creditos.png
      - assets\soma.png
      - assets\subtracao.png
      - assets\divisao.png
      - assets\multiplicacao.png
      - assets\parabens1.jpg
      - assets\parabens2.jpg
      - assets\parabens3.jpg
      - assets\consolacao1.jpg
      - assets\consolacao2.jpg
      - assets\background.jpeg
